##  register Test instructor 1
POST http://localhost:8085/api/v2/authen/register HTTP/1.1
Content-Type: application/json

{
    "username":"khthana@kmitl.ac.th",
    "password":"khthana@kmitl.ac.th",
    "level":"instructor",
    "email":"khthana@kmitl.ac.th",
    "title":"ผศ.",
    "firstname":"ธนา",
    "lastname":"หงษ์สุวรรณ"
}

###  register Test instructor 2
POST http://localhost:8085/api/v2/authen/register HTTP/1.1
Content-Type: application/json

{
    "username":"chompoonuch.ji@kmitl.ac.th",
    "password":"chompoonuch.ji@kmitl.ac.th",
    "level":"instructor",
    "email":"chompoonuch.ji@kmitl.ac.th",
    "title":"ผศ. ดร.",
    "firstname":"ชมพูนุท",
    "lastname":" จินจาคาม"
}


### register Test student 
POST http://localhost:8085/api/v2/authen/register HTTP/1.1
Content-Type: application/json
 
{
    "username":"63015146",
    "password":"63015146",
    "level":"student",
    "email":"63015146@kmitl.ac.th",
    "title":"นาย",
    "firstname":"รฐนนท์",
    "lastname":"แสงรุ่งสว่าง"
}
### register Test student 2
POST http://localhost:8085/api/v2/authen/register HTTP/1.1
Content-Type: application/json

{
    "username":"63015117",
    "password":"63015117",
    "level":"student",
    "email":"63015117@kmitl.ac.th",
    "title":"นาย",
    "firstname":"พชรพล",
    "lastname":"พรมแพง"
}



 
### LOGIN Test teacher ||instructor  1
POST http://localhost:8085/api/v2/authen/login HTTP/1.1
Content-Type: application/json

{
    "username": "khthana@kmitl.ac.th",
    "password" : "khthana@kmitl.ac.th"
}

 
### LOGIN Test teacher ||instructor  2
POST http://51.79.251.237:8085/api/v2/authen/login HTTP/1.1
Content-Type: application/json

{
    "username": "chompoonuch.ji@kmitl.ac.th",
    "password" : "chompoonuch.ji@kmitl.ac.th"
}




 
#### 
{
  "result": "ok",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibGV2ZWwiOiJub3JtYWwiLCJpYXQiOjE2ODIyMzkzNDZ9.z5TAAPXJPEkqZve6bSvOo3Cd6a1Ns24EiDyYNja66Hg",
  "username": "admin",
  "message": "{\"username\":\"admin\",\"password\":\"$2a$08$OQF3mPEsZVp0yVLEi4lSUugWnHW2vY9TQkI/NHFpp/hDSqFnWNMMy\",\"level\":\"normal\",\"createdAt\":\"2019-06-15T03:55:27.442Z\",\"updatedAt\":\"2019-06-15T03:55:27.442Z\"}"
}


### LOGIN Test student 1
POST http://localhost:8085/api/v2/authen/login HTTP/1.1
Content-Type: application/json

{
    "username": "63015144",
    "password" : "63015144"
}

### LOGIN Test student 2
POST http://localhost:8085/api/v2/authen/login HTTP/1.1
Content-Type: application/json

{
    "username": "63015117",
    "password" : "63015117"
}


### get profile 
GET http://localhost:8085/api/v2/authen/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODQ5NDI5NDF9.bZJ1WbN-696Xt-ejoyVVHuFauQAX8vI6H8XtBemc_xE


###  get profile instructor 
GET http://51.79.251.237:8085/api/v2/authen/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIwMjExNjJ9.HgbF7idQeoEHFNhaj84QSL8SLIylo9hJVUnXt-tGkRM



### Query all users 
GET http://localhost:8085/api/v2/authen/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIwMjExNjJ9.HgbF7idQeoEHFNhaj84QSL8SLIylo9hJVUnXt-tGkRM

