### Create the new course ||instructor  1
POST http://localhost:8085/api/v2/course/courses HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIxNjU0OTN9.l2WO2wbqml6AaJf6EBTT7Urs8102zlQITHtTHQW53p8
Content-Type: application/json

{  
    "id_code":"0107600924",
    "name":"NETWORK BASIC"
}

### Create the new course ||instructor  2
POST http://localhost:8085/api/v2/course/courses HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNob21wb29udWNoLmppQGttaXRsLmFjLnRoIiwibGV2ZWwiOiJpbnN0cnVjdG9yIiwiaWF0IjoxNjgyMjM1Mjk0fQ.q2k5o4NOig2d05P40SQ4hxHDqiUv7uJdG7BkM1x6Dcw
Content-Type: application/json

{  
    "id_code":"0107600922",
    "name":"Computer Organization And Assembly Language3123"
}



### update course ||instructor  1
PUT http://localhost:8085/api/v2/course/courses/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIzNDYxMDF9.atXNKTu-A8socQiss0ZTIapcdR4hf4NG-uMrZC-umHc
Content-Type: application/json

{   
    "id_code":"0107600923",
    "name":"Computer Organization And Assembly Language"
  
}


### get courses ||instructor  1
GET http://localhost:8085/api/v2/course/courses/6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIxNjU0OTN9.l2WO2wbqml6AaJf6EBTT7Urs8102zlQITHtTHQW53p8

### get courses ||instructor  2
GET http://localhost:8085/api/v2/course/courses/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNob21wb29udWNoLmppQGttaXRsLmFjLnRoIiwibGV2ZWwiOiJpbnN0cnVjdG9yIiwiaWF0IjoxNjgyMTY2MzExfQ.Om9NtL7XRUHmlhLPKxT5KWK4do54YhxIlagdqODnfZ0
### list courses ||instructor  1
GET http://localhost:8085/api/v2/course/courses HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIxNjU0OTN9.l2WO2wbqml6AaJf6EBTT7Urs8102zlQITHtTHQW53p8

### list courses ||instructor  2
GET http://localhost:8085/api/v2/course/courses HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNob21wb29udWNoLmppQGttaXRsLmFjLnRoIiwibGV2ZWwiOiJpbnN0cnVjdG9yIiwiaWF0IjoxNjgyMTY2MzExfQ.Om9NtL7XRUHmlhLPKxT5KWK4do54YhxIlagdqODnfZ0


### delete course ||instructor 
delete http://localhost:8085/api/v2/course/courses/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIxNjU0OTN9.l2WO2wbqml6AaJf6EBTT7Urs8102zlQITHtTHQW53p8


### Create a new quiz with the given name and associate it with the course   ||instructor 
POST http://localhost:8085/api/v2/course/courses/6/quizzes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIwMjExNjJ9.HgbF7idQeoEHFNhaj84QSL8SLIylo9hJVUnXt-tGkRM
Content-Type: application/json

{
  "name": "Example Quiz 2",
  "questions": [
    {
      "title": "Question 1",
      "answers": [
        {
          "body": "Answer 1",
          "isCorrect": true
        },
        {
          "body": "Answer 2",
          "isCorrect": false
        },
        {
          "body": "Answer 3",
          "isCorrect": false
        }
      ]
    },
    {
      "title": "Question 2",
      "answers": [
        {
          "body": "Answer 1",
          "isCorrect": true
        },
        {
          "body": "Answer 2",
          "isCorrect": false
        },
        {
          "body": "Answer 3",
          "isCorrect": false
        }
      ]
    }
  ]
}

 
###  update 
put http://localhost:8085/api/v2/test/courses/1/quizzes/20 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIwMjExNjJ9.HgbF7idQeoEHFNhaj84QSL8SLIylo9hJVUnXt-tGkRM
Content-Type: application/json

{
  "name": "Example Quiz 101",
  "questions": [
    {
      "title": "Question 101",
      "answers": [
        {
          "body": "Answer 101",
          "isCorrect": true
        },
        {
          "body": "Answer 101",
          "isCorrect": false
        },
        {
          "body": "Answer 3",
          "isCorrect": true
        }
      ]
    },
    {
      "title": "Question 101",
      "answers": [
        {
          "body": "Answer 1",
          "isCorrect": true
        },
        {
          "body": "Answer 101",
          "isCorrect": true
        },
        {
          "body": "Answer 3",
          "isCorrect": false
        }
      ]
    }
  ]
}

###  Delete Quiz: Allow instructors to delete a quiz
Delete http://localhost:8085/api/v2/test/courses/1/quizzes/22 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIwMjExNjJ9.HgbF7idQeoEHFNhaj84QSL8SLIylo9hJVUnXt-tGkRM

### Define a route to get a list of quizzes
GET http://localhost:8085/api/v2/course/courses/6/question HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodGhhbmFAa21pdGwuYWMudGgiLCJsZXZlbCI6Imluc3RydWN0b3IiLCJpYXQiOjE2ODIwMjExNjJ9.HgbF7idQeoEHFNhaj84QSL8SLIylo9hJVUnXt-tGkRM


###Test dropall
GET http://127.0.0.1:8085/api/v2/test/dropall HTTP/1.1
###Test creattable
GET http://127.0.0.1:8085/api/v2/test/creattable HTTP/1.1


